# closed days - usually weekends
closed_days = ["saturday", "sunday"]

# how many working hours should be assumed per day
working_hrs_in_day = 8

# public holidays, the list should cover project timelines
# you should have a safety margin such as a few months ahead
public_holidays = [
    # 2024
    {date="2024-01-01", name="New Year's Day"},
    {date="2024-01-06", name="Epiphany"},
    {date="2024-03-31", name="Easter Sunday"},
    {date="2024-04-01", name="Easter Monday"},
    {date="2024-05-01", name="May Day"},
    {date="2024-05-03", name="Constitution Day"},
    {date="2024-05-19", name="Whit Sunday"},
    {date="2024-05-30", name="Corpus Chriti"},
    {date="2024-08-15", name="Assumption Day"},
    {date="2024-11-01", name="All Saints' Day"},
    {date="2024-11-11", name="Independence Day"},
    {date="2024-12-25", name="Christmas Day"},
    {date="2024-12-26", name="St. Stephen's Day"},
    # 2025
    {date="2025-01-01", name="New Year's Day"},
    {date="2025-01-06", name="Epiphany"},
    {date="2025-04-20", name="Easter Sunday"},
    {date="2025-04-21", name="Easter Monday"},
    {date="2025-05-01", name="May Day"},
    {date="2025-05-03", name="Constitution Day"},
    {date="2025-06-08", name="Whit Sunday"},
    {date="2025-06-19", name="Corpus Chriti"},
    {date="2025-08-15", name="Assumption Day"},
    {date="2025-11-01", name="All Saints' Day"},
    {date="2025-11-11", name="Independence Day"},
    {date="2025-12-25", name="Christmas Day"},
    {date="2025-12-26", name="St. Stephen's Day"},
]
