# Project name
project_name = "Game development"
# When the project get started
start_date = "2024-10-01"
# Your team
team = [
    { name="Alicja", base_calendar="calendar_pl.toml", focus_factor=0.5, holidays="2024-10-7:2024-10-8, 2024-10-25", other_duties=""},
    { name="Mirek", base_calendar="calendar_pl.toml", focus_factor=0.7, holidays="2024-12-27", other_duties="2024-09-30:2024-10-05"},
    { name="Adam", base_calendar="calendar_pl.toml", focus_factor=0.6, holidays="2024-11-11:2024-11-17", other_duties=""},
]

tasks = [
    {id="T1", name="Game engine development", estimate=15},
    {id="T2", name="Game logic development", estimate=10, after="T1"},
    {id="T3", name="Assets and arts", estimate=15},
    {id="T4", name="QA", estimate=7, after="T2,T3"},
    {id="T5", name="Bug fixing", estimate=5, after="T2,T3"},
    {id="T6", name="Beta tests", estimate=4, after="T5"},
]

assignments = [
    {task="T1", owner="Mirek"},
    {task="T2", owner="Mirek"},
    {task="T3", owner="Alicja"},
    {task="T4", owner="Adam"},
    {task="T5", owner="Mirek", focus_factor=0.8},
    {task="T6", owner="Adam"},
]
